version: '3'
services: 
    proxy:
        build: .
        container_name: nginx_container
        restart: always
        ports:
        - "80:80"
networks:
    default:
        external:
            name: backend_default
